---
- name: Install picture editing tools
  apt:
    name: [ 'exif', 'webp' ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes